// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apigrpc/apigrpc.proto

package apigrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import api "spaceship/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpaceShipClient is the client API for SpaceShip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpaceShipClient interface {
	AuthenticateFingerprint(ctx context.Context, in *api.AuthenticateFingerprint, opts ...grpc.CallOption) (*api.Session, error)
	AuthenticateFacebook(ctx context.Context, in *api.AuthenticateFacebook, opts ...grpc.CallOption) (*api.Session, error)
	UpdateUser(ctx context.Context, in *api.UserUpdate, opts ...grpc.CallOption) (*api.User, error)
	UnlinkFacebook(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	AddNotificationToken(ctx context.Context, in *api.NotificationTokenUpdate, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateNotificationToken(ctx context.Context, in *api.NotificationTokenUpdate, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteNotificationToken(ctx context.Context, in *api.NotificationTokenUpdate, opts ...grpc.CallOption) (*empty.Empty, error)
	GetLeaderboard(ctx context.Context, in *api.LeaderboardRequest, opts ...grpc.CallOption) (*api.LeaderboardResponse, error)
	GetFriends(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*api.UserFriends, error)
	AddFriend(ctx context.Context, in *api.FriendRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteFriend(ctx context.Context, in *api.FriendRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	TestEcho(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*api.Session, error)
}

type spaceShipClient struct {
	cc *grpc.ClientConn
}

func NewSpaceShipClient(cc *grpc.ClientConn) SpaceShipClient {
	return &spaceShipClient{cc}
}

func (c *spaceShipClient) AuthenticateFingerprint(ctx context.Context, in *api.AuthenticateFingerprint, opts ...grpc.CallOption) (*api.Session, error) {
	out := new(api.Session)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/AuthenticateFingerprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) AuthenticateFacebook(ctx context.Context, in *api.AuthenticateFacebook, opts ...grpc.CallOption) (*api.Session, error) {
	out := new(api.Session)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/AuthenticateFacebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) UpdateUser(ctx context.Context, in *api.UserUpdate, opts ...grpc.CallOption) (*api.User, error) {
	out := new(api.User)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) UnlinkFacebook(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/UnlinkFacebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) AddNotificationToken(ctx context.Context, in *api.NotificationTokenUpdate, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/AddNotificationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) UpdateNotificationToken(ctx context.Context, in *api.NotificationTokenUpdate, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/UpdateNotificationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) DeleteNotificationToken(ctx context.Context, in *api.NotificationTokenUpdate, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/DeleteNotificationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) GetLeaderboard(ctx context.Context, in *api.LeaderboardRequest, opts ...grpc.CallOption) (*api.LeaderboardResponse, error) {
	out := new(api.LeaderboardResponse)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/GetLeaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) GetFriends(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*api.UserFriends, error) {
	out := new(api.UserFriends)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/GetFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) AddFriend(ctx context.Context, in *api.FriendRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/AddFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) DeleteFriend(ctx context.Context, in *api.FriendRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/DeleteFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceShipClient) TestEcho(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*api.Session, error) {
	out := new(api.Session)
	err := c.cc.Invoke(ctx, "/spaceship.api.SpaceShip/TestEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceShipServer is the server API for SpaceShip service.
type SpaceShipServer interface {
	AuthenticateFingerprint(context.Context, *api.AuthenticateFingerprint) (*api.Session, error)
	AuthenticateFacebook(context.Context, *api.AuthenticateFacebook) (*api.Session, error)
	UpdateUser(context.Context, *api.UserUpdate) (*api.User, error)
	UnlinkFacebook(context.Context, *empty.Empty) (*empty.Empty, error)
	AddNotificationToken(context.Context, *api.NotificationTokenUpdate) (*empty.Empty, error)
	UpdateNotificationToken(context.Context, *api.NotificationTokenUpdate) (*empty.Empty, error)
	DeleteNotificationToken(context.Context, *api.NotificationTokenUpdate) (*empty.Empty, error)
	GetLeaderboard(context.Context, *api.LeaderboardRequest) (*api.LeaderboardResponse, error)
	GetFriends(context.Context, *empty.Empty) (*api.UserFriends, error)
	AddFriend(context.Context, *api.FriendRequest) (*empty.Empty, error)
	DeleteFriend(context.Context, *api.FriendRequest) (*empty.Empty, error)
	TestEcho(context.Context, *empty.Empty) (*api.Session, error)
}

func RegisterSpaceShipServer(s *grpc.Server, srv SpaceShipServer) {
	s.RegisterService(&_SpaceShip_serviceDesc, srv)
}

func _SpaceShip_AuthenticateFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.AuthenticateFingerprint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).AuthenticateFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/AuthenticateFingerprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).AuthenticateFingerprint(ctx, req.(*api.AuthenticateFingerprint))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_AuthenticateFacebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.AuthenticateFacebook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).AuthenticateFacebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/AuthenticateFacebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).AuthenticateFacebook(ctx, req.(*api.AuthenticateFacebook))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.UserUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).UpdateUser(ctx, req.(*api.UserUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_UnlinkFacebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).UnlinkFacebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/UnlinkFacebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).UnlinkFacebook(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_AddNotificationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.NotificationTokenUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).AddNotificationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/AddNotificationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).AddNotificationToken(ctx, req.(*api.NotificationTokenUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_UpdateNotificationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.NotificationTokenUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).UpdateNotificationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/UpdateNotificationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).UpdateNotificationToken(ctx, req.(*api.NotificationTokenUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_DeleteNotificationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.NotificationTokenUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).DeleteNotificationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/DeleteNotificationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).DeleteNotificationToken(ctx, req.(*api.NotificationTokenUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.LeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/GetLeaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).GetLeaderboard(ctx, req.(*api.LeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/GetFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).GetFriends(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).AddFriend(ctx, req.(*api.FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/DeleteFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).DeleteFriend(ctx, req.(*api.FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceShip_TestEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceShipServer).TestEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spaceship.api.SpaceShip/TestEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceShipServer).TestEcho(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpaceShip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spaceship.api.SpaceShip",
	HandlerType: (*SpaceShipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateFingerprint",
			Handler:    _SpaceShip_AuthenticateFingerprint_Handler,
		},
		{
			MethodName: "AuthenticateFacebook",
			Handler:    _SpaceShip_AuthenticateFacebook_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _SpaceShip_UpdateUser_Handler,
		},
		{
			MethodName: "UnlinkFacebook",
			Handler:    _SpaceShip_UnlinkFacebook_Handler,
		},
		{
			MethodName: "AddNotificationToken",
			Handler:    _SpaceShip_AddNotificationToken_Handler,
		},
		{
			MethodName: "UpdateNotificationToken",
			Handler:    _SpaceShip_UpdateNotificationToken_Handler,
		},
		{
			MethodName: "DeleteNotificationToken",
			Handler:    _SpaceShip_DeleteNotificationToken_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _SpaceShip_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _SpaceShip_GetFriends_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _SpaceShip_AddFriend_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _SpaceShip_DeleteFriend_Handler,
		},
		{
			MethodName: "TestEcho",
			Handler:    _SpaceShip_TestEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apigrpc/apigrpc.proto",
}

func init() { proto.RegisterFile("apigrpc/apigrpc.proto", fileDescriptor_apigrpc_fbc79d8308ccf7df) }

var fileDescriptor_apigrpc_fbc79d8308ccf7df = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xd1, 0x6e, 0x23, 0x35,
	0x14, 0x65, 0xb2, 0x12, 0x34, 0xde, 0x6d, 0x37, 0xb8, 0xbb, 0x09, 0x3b, 0xec, 0x4a, 0xd9, 0x29,
	0x5a, 0xb1, 0xd1, 0xee, 0x38, 0xc9, 0x0a, 0xad, 0x94, 0x17, 0x48, 0xc4, 0xb6, 0x2a, 0xaa, 0x50,
	0x44, 0x1a, 0xa4, 0x16, 0x24, 0xe4, 0xcc, 0xdc, 0x4c, 0x4c, 0x12, 0xdb, 0x8c, 0x9d, 0x56, 0x55,
	0x14, 0x24, 0x40, 0xe2, 0x81, 0x17, 0x24, 0xf8, 0x03, 0x1e, 0x79, 0xe7, 0x13, 0xf8, 0x02, 0x7e,
	0x81, 0x0f, 0x41, 0xf6, 0x4c, 0xdb, 0x69, 0x9a, 0x49, 0x1f, 0x50, 0x5f, 0xc6, 0x9a, 0x7b, 0x8f,
	0xcf, 0x39, 0xf6, 0xb5, 0xaf, 0xd1, 0x43, 0x2a, 0x59, 0x14, 0xcb, 0x80, 0xa4, 0xa3, 0x2f, 0x63,
	0xa1, 0x05, 0xde, 0x54, 0x92, 0x06, 0xa0, 0x46, 0x4c, 0xfa, 0x54, 0x32, 0xf7, 0x71, 0x24, 0x44,
	0x34, 0x01, 0x03, 0x22, 0x94, 0x73, 0xa1, 0xa9, 0x66, 0x82, 0xab, 0x04, 0xec, 0xbe, 0x9f, 0x66,
	0xed, 0xdf, 0x60, 0x36, 0x24, 0x30, 0x95, 0xfa, 0x2c, 0x4d, 0xbe, 0xb0, 0x43, 0xf0, 0x32, 0x02,
	0xfe, 0x52, 0x9d, 0xd2, 0x28, 0x82, 0x98, 0x08, 0x69, 0xa7, 0xaf, 0xa0, 0xaa, 0x5c, 0xe8, 0x26,
	0x5a, 0x92, 0x25, 0x89, 0xe6, 0xcf, 0x77, 0x51, 0xb1, 0x67, 0x72, 0xbd, 0x11, 0x93, 0xf8, 0x17,
	0x07, 0x55, 0xda, 0x33, 0x3d, 0x02, 0xae, 0x59, 0x40, 0x35, 0xec, 0x32, 0x1e, 0x41, 0x2c, 0x63,
	0xc6, 0x35, 0x7e, 0xe6, 0x5f, 0xf1, 0xee, 0xe7, 0xe0, 0xdc, 0xf2, 0x12, 0xae, 0x07, 0x4a, 0x31,
	0xc1, 0x3d, 0xf2, 0xe3, 0x3f, 0xff, 0xfe, 0x5e, 0x78, 0xee, 0x7d, 0x40, 0x4e, 0x1a, 0x84, 0x06,
	0x81, 0x98, 0x71, 0x4d, 0x68, 0x86, 0x84, 0x0c, 0x2f, 0x59, 0x5a, 0x4e, 0x0d, 0xff, 0xe0, 0xa0,
	0x07, 0x57, 0x44, 0x68, 0x00, 0x03, 0x21, 0xc6, 0x78, 0x67, 0x9d, 0x93, 0x14, 0x94, 0x6b, 0xe3,
	0x85, 0xb5, 0xf1, 0xcc, 0x7b, 0x9a, 0x6f, 0x23, 0xa5, 0x30, 0x1e, 0xbe, 0x42, 0xa8, 0x2f, 0x43,
	0xaa, 0xa1, 0xaf, 0x20, 0xc6, 0x8f, 0x96, 0x38, 0x4d, 0x30, 0x49, 0xbb, 0xdb, 0x2b, 0x52, 0xde,
	0x13, 0xab, 0x55, 0x71, 0x71, 0x56, 0x6b, 0x66, 0x27, 0x18, 0xf2, 0x31, 0xda, 0xea, 0xf3, 0x09,
	0xe3, 0xe3, 0x8b, 0x95, 0x95, 0xfd, 0xa4, 0xe4, 0xfe, 0x79, 0xc9, 0xfd, 0x37, 0xa6, 0xe4, 0x6e,
	0x4e, 0xdc, 0x7b, 0x6e, 0x05, 0x76, 0x6a, 0x37, 0x2f, 0x06, 0xcf, 0xd1, 0x83, 0x76, 0x18, 0x7e,
	0x2e, 0x34, 0x1b, 0x9a, 0x0c, 0x13, 0xfc, 0x50, 0x8c, 0x81, 0x5f, 0x2b, 0xeb, 0x35, 0x44, 0xba,
	0xc0, 0x3c, 0x0b, 0x3b, 0xd6, 0xc2, 0x13, 0xef, 0xbd, 0xac, 0x05, 0x9e, 0x21, 0x31, 0x2b, 0xfd,
	0x1e, 0x55, 0x12, 0x9a, 0x5b, 0xd3, 0x77, 0xd7, 0xea, 0xff, 0xe4, 0xa0, 0xca, 0xa7, 0x30, 0x81,
	0xdb, 0x30, 0xf0, 0xa1, 0x35, 0xe0, 0xd5, 0xaa, 0x79, 0x06, 0xc8, 0x5c, 0x1b, 0x9a, 0x05, 0xfe,
	0xcb, 0x41, 0x5b, 0x7b, 0xa0, 0x0f, 0x80, 0x86, 0x10, 0x0f, 0x04, 0x8d, 0x43, 0xfc, 0x74, 0x49,
	0x3c, 0x93, 0xfb, 0x02, 0xbe, 0x9b, 0x81, 0xd2, 0xae, 0xb7, 0x0e, 0xa2, 0xa4, 0xe0, 0x0a, 0xbc,
	0xaf, 0xad, 0x87, 0x2f, 0xb1, 0x67, 0x3c, 0x4c, 0x2e, 0x01, 0x64, 0xae, 0xcf, 0x24, 0x2c, 0xc8,
	0x54, 0x84, 0x40, 0xe6, 0xe6, 0xbb, 0x38, 0xae, 0x63, 0xff, 0x66, 0x14, 0x91, 0x34, 0x02, 0x32,
	0x37, 0xdf, 0x05, 0xee, 0x23, 0xb4, 0x07, 0x7a, 0x37, 0x66, 0xc0, 0x43, 0x95, 0x7b, 0x46, 0xdd,
	0x15, 0x37, 0x20, 0x9d, 0xe3, 0x6d, 0x5b, 0x7f, 0x9b, 0xf8, 0xae, 0x51, 0x1e, 0xa6, 0x44, 0x47,
	0xa8, 0xd8, 0x0e, 0xc3, 0x04, 0x82, 0x1f, 0x2f, 0xcd, 0x4e, 0xc2, 0xe7, 0x7b, 0x90, 0xb7, 0xf7,
	0x65, 0xcb, 0x5b, 0xf2, 0xb2, 0xbc, 0xa6, 0xde, 0x01, 0xba, 0x97, 0x94, 0xfb, 0x7f, 0xb1, 0xa7,
	0xd7, 0xb7, 0xf6, 0x30, 0xc3, 0x4e, 0xe6, 0x33, 0x05, 0xf1, 0x37, 0x2c, 0x5c, 0xe0, 0x03, 0xb4,
	0x71, 0x08, 0x4a, 0xbf, 0x09, 0x46, 0x62, 0xcd, 0xc5, 0x5d, 0xdd, 0x85, 0x4a, 0x96, 0x1a, 0xe1,
	0x0d, 0x43, 0x0d, 0xc1, 0x48, 0x74, 0x7e, 0x2d, 0xfc, 0xd6, 0xfe, 0xdb, 0xc1, 0x47, 0xe8, 0x5d,
	0xdb, 0x8e, 0xab, 0xa6, 0x1f, 0x57, 0xdb, 0xdd, 0xfd, 0xea, 0x49, 0xc3, 0xfb, 0x18, 0x95, 0xdb,
	0xdd, 0x6e, 0xaf, 0xba, 0xcf, 0x87, 0x22, 0x9e, 0xda, 0x43, 0x55, 0x3d, 0x84, 0x60, 0xe4, 0xe3,
	0xed, 0x91, 0xd6, 0x52, 0xb5, 0x08, 0xa1, 0x52, 0x2a, 0x3f, 0x10, 0x53, 0x5f, 0xc7, 0x6e, 0x89,
	0xf1, 0xa1, 0xf8, 0x24, 0x13, 0x69, 0xde, 0x69, 0xf8, 0x75, 0x77, 0xab, 0xd1, 0x7c, 0xed, 0xd7,
	0xfd, 0xba, 0xdf, 0x68, 0xbd, 0x7e, 0xf5, 0x51, 0xbd, 0xe6, 0x38, 0xcd, 0x12, 0x95, 0x72, 0x72,
	0x7e, 0x4c, 0xbf, 0x55, 0x82, 0xb7, 0xae, 0x45, 0x8e, 0xab, 0xe8, 0x3e, 0x2a, 0x76, 0xa8, 0x62,
	0x81, 0xe9, 0xb3, 0xb8, 0xb0, 0xe1, 0xa0, 0x4d, 0x54, 0xec, 0x00, 0x8d, 0x21, 0xfe, 0xec, 0x54,
	0xe3, 0xb7, 0x06, 0xf7, 0x97, 0x02, 0xe8, 0x91, 0x8e, 0xad, 0xb2, 0xb5, 0x70, 0x65, 0x03, 0x3a,
	0xf7, 0x2e, 0x1e, 0x9b, 0xb6, 0x64, 0x5d, 0xe7, 0xf8, 0x9d, 0xf4, 0x7d, 0xfc, 0xa3, 0x70, 0xa7,
	0xd7, 0xeb, 0xfe, 0x59, 0xb8, 0x7c, 0x8c, 0x06, 0x6f, 0xdb, 0xbd, 0x7c, 0xf5, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7d, 0xe1, 0xd3, 0xee, 0x4b, 0x07, 0x00, 0x00,
}
