// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socketapi/socketapi.proto

package socketapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "spaceship/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The selection of possible error codes.
type Error_Code int32

const (
	// An unexpected result from the server.
	Error_RUNTIME_EXCEPTION Error_Code = 0
	// The server received a message which is not recognised.
	Error_UNRECOGNIZED_PAYLOAD Error_Code = 1
	// A message was expected but contains no content.
	Error_MISSING_PAYLOAD Error_Code = 2
	// Fields in the message have an invalid format.
	Error_BAD_INPUT Error_Code = 3
	// The match id was not found.
	Error_MATCH_NOT_FOUND Error_Code = 4
	// The match join was rejected.
	Error_MATCH_JOIN_REJECTED Error_Code = 5
	// The runtime function does not exist on the server.
	Error_RUNTIME_FUNCTION_NOT_FOUND Error_Code = 6
	// The runtime function executed with an error.
	Error_RUNTIME_FUNCTION_EXCEPTION Error_Code = 7
)

var Error_Code_name = map[int32]string{
	0: "RUNTIME_EXCEPTION",
	1: "UNRECOGNIZED_PAYLOAD",
	2: "MISSING_PAYLOAD",
	3: "BAD_INPUT",
	4: "MATCH_NOT_FOUND",
	5: "MATCH_JOIN_REJECTED",
	6: "RUNTIME_FUNCTION_NOT_FOUND",
	7: "RUNTIME_FUNCTION_EXCEPTION",
}
var Error_Code_value = map[string]int32{
	"RUNTIME_EXCEPTION":          0,
	"UNRECOGNIZED_PAYLOAD":       1,
	"MISSING_PAYLOAD":            2,
	"BAD_INPUT":                  3,
	"MATCH_NOT_FOUND":            4,
	"MATCH_JOIN_REJECTED":        5,
	"RUNTIME_FUNCTION_NOT_FOUND": 6,
	"RUNTIME_FUNCTION_EXCEPTION": 7,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}
func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_socketapi_cb22454ccdc1928b, []int{1, 0}
}

type Envelope struct {
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Envelope_Error
	//	*Envelope_MatchStart
	Message              isEnvelope_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_socketapi_cb22454ccdc1928b, []int{0}
}
func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (dst *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(dst, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Envelope_MatchStart struct {
	MatchStart *MatchStart `protobuf:"bytes,3,opt,name=match_start,json=matchStart,proto3,oneof"`
}

func (*Envelope_Error) isEnvelope_Message() {}

func (*Envelope_MatchStart) isEnvelope_Message() {}

func (m *Envelope) GetMessage() isEnvelope_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetError() *Error {
	if x, ok := m.GetMessage().(*Envelope_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Envelope) GetMatchStart() *MatchStart {
	if x, ok := m.GetMessage().(*Envelope_MatchStart); ok {
		return x.MatchStart
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Envelope) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Envelope_OneofMarshaler, _Envelope_OneofUnmarshaler, _Envelope_OneofSizer, []interface{}{
		(*Envelope_Error)(nil),
		(*Envelope_MatchStart)(nil),
	}
}

func _Envelope_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Envelope)
	// message
	switch x := m.Message.(type) {
	case *Envelope_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *Envelope_MatchStart:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchStart); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Envelope.Message has unexpected type %T", x)
	}
	return nil
}

func _Envelope_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Envelope)
	switch tag {
	case 2: // message.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_Error{msg}
		return true, err
	case 3: // message.match_start
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchStart)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchStart{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Envelope_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Envelope)
	// message
	switch x := m.Message.(type) {
	case *Envelope_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchStart:
		s := proto.Size(x.MatchStart)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A logical error which may occur on the server.
type Error struct {
	// The error code which should be one of "Error.Code" enums.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A message in English to help developers debug the response.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Additional error details which may be different for each response.
	Context              map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_socketapi_cb22454ccdc1928b, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

type MatchStart struct {
	GameName             string   `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchStart) Reset()         { *m = MatchStart{} }
func (m *MatchStart) String() string { return proto.CompactTextString(m) }
func (*MatchStart) ProtoMessage()    {}
func (*MatchStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_socketapi_cb22454ccdc1928b, []int{2}
}
func (m *MatchStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchStart.Unmarshal(m, b)
}
func (m *MatchStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchStart.Marshal(b, m, deterministic)
}
func (dst *MatchStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchStart.Merge(dst, src)
}
func (m *MatchStart) XXX_Size() int {
	return xxx_messageInfo_MatchStart.Size(m)
}
func (m *MatchStart) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchStart.DiscardUnknown(m)
}

var xxx_messageInfo_MatchStart proto.InternalMessageInfo

func (m *MatchStart) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func init() {
	proto.RegisterType((*Envelope)(nil), "spaceship.socket.Envelope")
	proto.RegisterType((*Error)(nil), "spaceship.socket.Error")
	proto.RegisterMapType((map[string]string)(nil), "spaceship.socket.Error.ContextEntry")
	proto.RegisterType((*MatchStart)(nil), "spaceship.socket.MatchStart")
	proto.RegisterEnum("spaceship.socket.Error_Code", Error_Code_name, Error_Code_value)
}

func init() {
	proto.RegisterFile("socketapi/socketapi.proto", fileDescriptor_socketapi_cb22454ccdc1928b)
}

var fileDescriptor_socketapi_cb22454ccdc1928b = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x9d, 0xa4, 0xa9, 0x27, 0xa0, 0x9a, 0x6d, 0x51, 0x42, 0x40, 0x6d, 0x15, 0x71, 0x08,
	0x17, 0x47, 0x2a, 0x17, 0xd4, 0x03, 0x28, 0x71, 0xb6, 0x8d, 0x2b, 0xb2, 0x0e, 0xb6, 0x23, 0x41,
	0x2f, 0xd6, 0xd6, 0x5d, 0x12, 0x2b, 0x71, 0x76, 0x65, 0x6f, 0x0b, 0x79, 0x14, 0xae, 0x1c, 0x79,
	0x13, 0x1e, 0x0a, 0x09, 0xad, 0xdd, 0xb8, 0x55, 0x0b, 0xb7, 0x99, 0xef, 0x67, 0xe7, 0xd3, 0x67,
	0xc3, 0x8b, 0x8c, 0x47, 0x0b, 0x26, 0xa9, 0x88, 0x7b, 0xe5, 0x64, 0x89, 0x94, 0x4b, 0x8e, 0xcc,
	0x4c, 0xd0, 0x88, 0x65, 0xf3, 0x58, 0x58, 0x05, 0xd5, 0x3e, 0x9c, 0x71, 0x3e, 0x5b, 0xb2, 0x5e,
	0xce, 0x5f, 0x5e, 0x7f, 0xed, 0xc9, 0x38, 0x61, 0x99, 0xa4, 0x89, 0x28, 0x2c, 0xed, 0x83, 0x87,
	0x82, 0x6f, 0x29, 0x15, 0x82, 0xa5, 0xd9, 0x2d, 0xdf, 0x2c, 0x9f, 0xec, 0xa9, 0x8b, 0xe5, 0xad,
	0xce, 0x0f, 0x0d, 0x76, 0xf0, 0xea, 0x86, 0x2d, 0xb9, 0x60, 0xc8, 0x84, 0x4a, 0x14, 0x5f, 0xb5,
	0xb4, 0x23, 0xad, 0x6b, 0x78, 0x6a, 0x44, 0x3d, 0xa8, 0xb1, 0x34, 0xe5, 0x69, 0x4b, 0x3f, 0xd2,
	0xba, 0x8d, 0xe3, 0xa6, 0xf5, 0x30, 0x9a, 0x85, 0x15, 0x3d, 0xda, 0xf2, 0x0a, 0x1d, 0xfa, 0x00,
	0x8d, 0x84, 0xca, 0x68, 0x1e, 0x66, 0x92, 0xa6, 0xb2, 0x55, 0xc9, 0x6d, 0xaf, 0x1e, 0xdb, 0xc6,
	0x4a, 0xe4, 0x2b, 0xcd, 0x68, 0xcb, 0x83, 0xa4, 0xdc, 0x06, 0x06, 0xd4, 0x13, 0x96, 0x65, 0x74,
	0xc6, 0x3a, 0x7f, 0x74, 0xa8, 0xe5, 0xcf, 0x23, 0x04, 0xd5, 0x88, 0x5f, 0xb1, 0x3c, 0x59, 0xcd,
	0xcb, 0x67, 0xd4, 0x2a, 0x85, 0x79, 0x38, 0xc3, 0xdb, 0xac, 0xe8, 0x3d, 0xd4, 0x23, 0xbe, 0x92,
	0xec, 0xbb, 0xba, 0x5f, 0xe9, 0x36, 0x8e, 0x5f, 0xff, 0x27, 0xb6, 0x65, 0x17, 0x32, 0xbc, 0x92,
	0xe9, 0xda, 0xdb, 0x98, 0xda, 0x27, 0xf0, 0xe4, 0x3e, 0xa1, 0x6a, 0x59, 0xb0, 0xf5, 0xa6, 0x96,
	0x05, 0x5b, 0xa3, 0x7d, 0xa8, 0xdd, 0xd0, 0xe5, 0xf5, 0xe6, 0x72, 0xb1, 0x9c, 0xe8, 0xef, 0xb4,
	0xce, 0x6f, 0x0d, 0xaa, 0xb6, 0x8a, 0xf7, 0x1c, 0x9e, 0x79, 0x53, 0x12, 0x38, 0x63, 0x1c, 0xe2,
	0xcf, 0x36, 0x9e, 0x04, 0x8e, 0x4b, 0xcc, 0x2d, 0xd4, 0x82, 0xfd, 0x29, 0xf1, 0xb0, 0xed, 0x9e,
	0x11, 0xe7, 0x02, 0x0f, 0xc3, 0x49, 0xff, 0xcb, 0x47, 0xb7, 0x3f, 0x34, 0x35, 0xb4, 0x07, 0xbb,
	0x63, 0xc7, 0xf7, 0x1d, 0x72, 0x56, 0x82, 0x3a, 0x7a, 0x0a, 0xc6, 0xa0, 0x3f, 0x0c, 0x1d, 0x32,
	0x99, 0x06, 0x66, 0x25, 0xd7, 0xf4, 0x03, 0x7b, 0x14, 0x12, 0x37, 0x08, 0x4f, 0xdd, 0x29, 0x19,
	0x9a, 0x55, 0xd4, 0x84, 0xbd, 0x02, 0x3c, 0x77, 0x1d, 0x12, 0x7a, 0xf8, 0x1c, 0xdb, 0x01, 0x1e,
	0x9a, 0x35, 0x74, 0x00, 0xed, 0x4d, 0x84, 0xd3, 0x29, 0xb1, 0x55, 0x82, 0x7b, 0xc6, 0xed, 0x7f,
	0xf2, 0x77, 0x59, 0xeb, 0x9d, 0x37, 0x00, 0x77, 0x9f, 0x09, 0xbd, 0x04, 0x63, 0x46, 0x13, 0x16,
	0xae, 0x68, 0xc2, 0x6e, 0xbb, 0xd8, 0x51, 0x00, 0xa1, 0x09, 0x1b, 0x7c, 0x82, 0x43, 0x99, 0x5a,
	0x11, 0x4f, 0x2c, 0x2a, 0x44, 0xf6, 0xa8, 0x6e, 0x2a, 0xe2, 0xc1, 0xae, 0xaf, 0x40, 0x7f, 0x1e,
	0x0b, 0x3f, 0xc7, 0x26, 0xda, 0x85, 0x51, 0xb2, 0x3f, 0xf5, 0x8a, 0xef, 0x4f, 0x7e, 0xe9, 0x46,
	0x29, 0xba, 0xdc, 0xce, 0x7f, 0xd0, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x12, 0x29,
	0xcf, 0x29, 0x03, 0x00, 0x00,
}
