// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateFingerprint struct {
	Fingerprint          string   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateFingerprint) Reset()         { *m = AuthenticateFingerprint{} }
func (m *AuthenticateFingerprint) String() string { return proto.CompactTextString(m) }
func (*AuthenticateFingerprint) ProtoMessage()    {}
func (*AuthenticateFingerprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{0}
}
func (m *AuthenticateFingerprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateFingerprint.Unmarshal(m, b)
}
func (m *AuthenticateFingerprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateFingerprint.Marshal(b, m, deterministic)
}
func (dst *AuthenticateFingerprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateFingerprint.Merge(dst, src)
}
func (m *AuthenticateFingerprint) XXX_Size() int {
	return xxx_messageInfo_AuthenticateFingerprint.Size(m)
}
func (m *AuthenticateFingerprint) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateFingerprint.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateFingerprint proto.InternalMessageInfo

func (m *AuthenticateFingerprint) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

type AuthenticateFacebook struct {
	Fingerprint          string   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateFacebook) Reset()         { *m = AuthenticateFacebook{} }
func (m *AuthenticateFacebook) String() string { return proto.CompactTextString(m) }
func (*AuthenticateFacebook) ProtoMessage()    {}
func (*AuthenticateFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{1}
}
func (m *AuthenticateFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateFacebook.Unmarshal(m, b)
}
func (m *AuthenticateFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateFacebook.Marshal(b, m, deterministic)
}
func (dst *AuthenticateFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateFacebook.Merge(dst, src)
}
func (m *AuthenticateFacebook) XXX_Size() int {
	return xxx_messageInfo_AuthenticateFacebook.Size(m)
}
func (m *AuthenticateFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateFacebook proto.InternalMessageInfo

func (m *AuthenticateFacebook) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *AuthenticateFacebook) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	// The id of the user's account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The username of the user's account.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The fingerprint parameter for the user
	Fingerprint string `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The display name of the user.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A URL for an avatar image.
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// Additional information stored as a JSON object.
	Metadata string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The Facebook id in the user's account.
	FacebookId string `protobuf:"bytes,7,opt,name=facebook_id,json=facebookId,proto3" json:"facebook_id,omitempty"`
	// Indicates whether the user is currently online.
	Online bool `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	// The UNIX time when the user was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The UNIX time when the user was last updated.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *User) GetFacebookId() string {
	if m != nil {
		return m.FacebookId
	}
	return ""
}

func (m *User) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type UserUpdate struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdate) Reset()         { *m = UserUpdate{} }
func (m *UserUpdate) String() string { return proto.CompactTextString(m) }
func (*UserUpdate) ProtoMessage()    {}
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{3}
}
func (m *UserUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdate.Unmarshal(m, b)
}
func (m *UserUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdate.Marshal(b, m, deterministic)
}
func (dst *UserUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdate.Merge(dst, src)
}
func (m *UserUpdate) XXX_Size() int {
	return xxx_messageInfo_UserUpdate.Size(m)
}
func (m *UserUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdate proto.InternalMessageInfo

func (m *UserUpdate) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserUpdate) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type Session struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{4}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Leaderboard struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Score                int64    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leaderboard) Reset()         { *m = Leaderboard{} }
func (m *Leaderboard) String() string { return proto.CompactTextString(m) }
func (*Leaderboard) ProtoMessage()    {}
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{5}
}
func (m *Leaderboard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leaderboard.Unmarshal(m, b)
}
func (m *Leaderboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leaderboard.Marshal(b, m, deterministic)
}
func (dst *Leaderboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leaderboard.Merge(dst, src)
}
func (m *Leaderboard) XXX_Size() int {
	return xxx_messageInfo_Leaderboard.Size(m)
}
func (m *Leaderboard) XXX_DiscardUnknown() {
	xxx_messageInfo_Leaderboard.DiscardUnknown(m)
}

var xxx_messageInfo_Leaderboard proto.InternalMessageInfo

func (m *Leaderboard) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Leaderboard) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type LeaderboardRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Page                 string   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderboardRequest) Reset()         { *m = LeaderboardRequest{} }
func (m *LeaderboardRequest) String() string { return proto.CompactTextString(m) }
func (*LeaderboardRequest) ProtoMessage()    {}
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{6}
}
func (m *LeaderboardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardRequest.Unmarshal(m, b)
}
func (m *LeaderboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardRequest.Marshal(b, m, deterministic)
}
func (dst *LeaderboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardRequest.Merge(dst, src)
}
func (m *LeaderboardRequest) XXX_Size() int {
	return xxx_messageInfo_LeaderboardRequest.Size(m)
}
func (m *LeaderboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardRequest proto.InternalMessageInfo

func (m *LeaderboardRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LeaderboardRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *LeaderboardRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

type LeaderboardResponse struct {
	Items                []*Leaderboard `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ItemCount            int32          `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Page                 int32          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	HasNextPage          bool           `protobuf:"varint,4,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LeaderboardResponse) Reset()         { *m = LeaderboardResponse{} }
func (m *LeaderboardResponse) String() string { return proto.CompactTextString(m) }
func (*LeaderboardResponse) ProtoMessage()    {}
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a0068325bf6cf5c9, []int{7}
}
func (m *LeaderboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardResponse.Unmarshal(m, b)
}
func (m *LeaderboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardResponse.Marshal(b, m, deterministic)
}
func (dst *LeaderboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardResponse.Merge(dst, src)
}
func (m *LeaderboardResponse) XXX_Size() int {
	return xxx_messageInfo_LeaderboardResponse.Size(m)
}
func (m *LeaderboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardResponse proto.InternalMessageInfo

func (m *LeaderboardResponse) GetItems() []*Leaderboard {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *LeaderboardResponse) GetItemCount() int32 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

func (m *LeaderboardResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *LeaderboardResponse) GetHasNextPage() bool {
	if m != nil {
		return m.HasNextPage
	}
	return false
}

func init() {
	proto.RegisterType((*AuthenticateFingerprint)(nil), "spaceship.api.AuthenticateFingerprint")
	proto.RegisterType((*AuthenticateFacebook)(nil), "spaceship.api.AuthenticateFacebook")
	proto.RegisterType((*User)(nil), "spaceship.api.User")
	proto.RegisterType((*UserUpdate)(nil), "spaceship.api.UserUpdate")
	proto.RegisterType((*Session)(nil), "spaceship.api.Session")
	proto.RegisterType((*Leaderboard)(nil), "spaceship.api.Leaderboard")
	proto.RegisterType((*LeaderboardRequest)(nil), "spaceship.api.LeaderboardRequest")
	proto.RegisterType((*LeaderboardResponse)(nil), "spaceship.api.LeaderboardResponse")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_api_a0068325bf6cf5c9) }

var fileDescriptor_api_a0068325bf6cf5c9 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0xdc, 0x30,
	0x10, 0x55, 0xb2, 0x1f, 0xb0, 0x13, 0xe8, 0xc1, 0x20, 0x9a, 0x22, 0x55, 0x6c, 0x73, 0x29, 0xa7,
	0x50, 0xd1, 0x23, 0x27, 0xa8, 0xd4, 0x0f, 0x09, 0xa1, 0x55, 0xb6, 0x5c, 0x7a, 0x89, 0x66, 0x93,
	0x61, 0xd7, 0x62, 0x13, 0xbb, 0xb6, 0x53, 0xc1, 0x9f, 0xe9, 0xa1, 0xc7, 0xfe, 0xaf, 0xfe, 0x8f,
	0xca, 0x76, 0x42, 0x49, 0x57, 0x15, 0xea, 0x6d, 0xde, 0x9b, 0x79, 0xf3, 0xec, 0x99, 0x81, 0x5d,
	0x94, 0xfc, 0x04, 0x25, 0x4f, 0xa5, 0x12, 0x46, 0xb0, 0x5d, 0x2d, 0xb1, 0x20, 0xbd, 0xe2, 0x32,
	0x45, 0xc9, 0x0f, 0x8f, 0x96, 0x42, 0x2c, 0xd7, 0x74, 0xe2, 0x92, 0x8b, 0xe6, 0xe6, 0xc4, 0xf0,
	0x8a, 0xb4, 0xc1, 0x4a, 0xfa, 0xfa, 0xe4, 0x0c, 0x9e, 0x9f, 0x37, 0x66, 0x45, 0xb5, 0xe1, 0x05,
	0x1a, 0x7a, 0xcf, 0xeb, 0x25, 0x29, 0xa9, 0x78, 0x6d, 0xd8, 0x14, 0xa2, 0x9b, 0x3f, 0x30, 0x0e,
	0xa6, 0xc1, 0xf1, 0x24, 0x7b, 0x4c, 0x25, 0x57, 0xb0, 0xdf, 0x13, 0x63, 0x41, 0x0b, 0x21, 0x6e,
	0x9f, 0x56, 0xb2, 0x7d, 0x18, 0x19, 0x71, 0x4b, 0x75, 0x1c, 0xba, 0x9c, 0x07, 0xc9, 0xaf, 0x10,
	0x86, 0xd7, 0x9a, 0x14, 0x7b, 0x06, 0x21, 0x2f, 0x5b, 0x5d, 0xc8, 0x4b, 0x76, 0x08, 0xdb, 0x8d,
	0x26, 0x55, 0x63, 0x45, 0xad, 0xe2, 0x01, 0xff, 0x6d, 0x36, 0xd8, 0x34, 0x7b, 0x05, 0x3b, 0x25,
	0xd7, 0x72, 0x8d, 0xf7, 0xb9, 0xeb, 0x30, 0xf4, 0x25, 0x2d, 0x77, 0x65, 0x9b, 0xbc, 0x04, 0xc0,
	0x6f, 0x68, 0x50, 0xe5, 0x8d, 0x5a, 0xc7, 0x23, 0x57, 0x30, 0xf1, 0xcc, 0xb5, 0x5a, 0x5b, 0xff,
	0x8a, 0x0c, 0x96, 0x68, 0x30, 0x1e, 0x7b, 0xff, 0x0e, 0xb3, 0x23, 0x88, 0x6e, 0xda, 0x8f, 0xe7,
	0xbc, 0x8c, 0xb7, 0x5c, 0x1a, 0x3a, 0xea, 0x53, 0xc9, 0x0e, 0x60, 0x2c, 0xea, 0x35, 0xaf, 0x29,
	0xde, 0x9e, 0x06, 0xc7, 0xdb, 0x59, 0x8b, 0xd8, 0x19, 0x44, 0x85, 0x22, 0x34, 0x94, 0xdb, 0xa5,
	0xc4, 0x93, 0x69, 0x70, 0x1c, 0x9d, 0x1e, 0xa6, 0x7e, 0x63, 0x69, 0xb7, 0xb1, 0xf4, 0x73, 0xb7,
	0xb1, 0x0c, 0x7c, 0xb9, 0x25, 0xac, 0xb8, 0x91, 0xe5, 0x83, 0x18, 0x9e, 0x16, 0xfb, 0x72, 0x4b,
	0x24, 0x1f, 0x00, 0xec, 0x98, 0xaf, 0x1d, 0xb3, 0x31, 0x9e, 0x60, 0x73, 0x3c, 0x07, 0x30, 0xf6,
	0xc3, 0x68, 0xa7, 0xdf, 0xa2, 0xe4, 0x23, 0x6c, 0xcd, 0x49, 0x6b, 0x2e, 0x6a, 0xf6, 0x1a, 0x86,
	0x76, 0x25, 0x4e, 0x1d, 0x9d, 0xee, 0xa5, 0xbd, 0x3b, 0x4c, 0xad, 0x5d, 0xe6, 0x0a, 0xfe, 0xb1,
	0xfa, 0x4b, 0x88, 0x2e, 0x09, 0x4b, 0x52, 0x0b, 0x81, 0xaa, 0xfc, 0xaf, 0x6e, 0xba, 0x10, 0xca,
	0x9f, 0xc5, 0x20, 0xf3, 0x20, 0x99, 0x01, 0x7b, 0xd4, 0x2d, 0xa3, 0xaf, 0x0d, 0x69, 0xc3, 0x18,
	0x0c, 0xcd, 0xbd, 0xec, 0x3e, 0xe8, 0x62, 0xcb, 0x55, 0xa2, 0xec, 0xae, 0xca, 0xc5, 0x96, 0x93,
	0xb8, 0xa4, 0xf6, 0x94, 0x5c, 0x9c, 0x7c, 0x0f, 0x60, 0xaf, 0xd7, 0x52, 0x4b, 0x51, 0x6b, 0x62,
	0x6f, 0x60, 0xc4, 0x0d, 0x55, 0x3a, 0x0e, 0xa6, 0x03, 0xb7, 0x81, 0xfe, 0x4b, 0x1f, 0x4b, 0x7c,
	0xa1, 0x3d, 0x35, 0x1b, 0xe4, 0x85, 0x68, 0x6a, 0xe3, 0x7c, 0x47, 0xd9, 0xc4, 0x32, 0xef, 0x2c,
	0xd1, 0x33, 0x1f, 0x79, 0x73, 0x96, 0xc0, 0xee, 0x0a, 0x75, 0x5e, 0xd3, 0x9d, 0xc9, 0x5d, 0x72,
	0xe8, 0x0e, 0x29, 0x5a, 0xa1, 0xbe, 0xa2, 0x3b, 0x33, 0xc3, 0x25, 0x5d, 0x5c, 0xc0, 0x0b, 0xa3,
	0xd2, 0x42, 0x54, 0x29, 0x4a, 0xa9, 0xfb, 0xcf, 0xb8, 0xd8, 0x99, 0x5b, 0x38, 0x5f, 0x71, 0x79,
	0x2e, 0xf9, 0x2c, 0xf8, 0x32, 0x40, 0xc9, 0x7f, 0x84, 0x83, 0xf9, 0x7c, 0xf6, 0x33, 0x9c, 0x3c,
	0xe4, 0x16, 0x63, 0x77, 0x37, 0x6f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x2c, 0xa6, 0x63,
	0x54, 0x04, 0x00, 0x00,
}
