// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateFingerprint struct {
	Fingerprint          string   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateFingerprint) Reset()         { *m = AuthenticateFingerprint{} }
func (m *AuthenticateFingerprint) String() string { return proto.CompactTextString(m) }
func (*AuthenticateFingerprint) ProtoMessage()    {}
func (*AuthenticateFingerprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46a5b8bd97fe2993, []int{0}
}
func (m *AuthenticateFingerprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateFingerprint.Unmarshal(m, b)
}
func (m *AuthenticateFingerprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateFingerprint.Marshal(b, m, deterministic)
}
func (dst *AuthenticateFingerprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateFingerprint.Merge(dst, src)
}
func (m *AuthenticateFingerprint) XXX_Size() int {
	return xxx_messageInfo_AuthenticateFingerprint.Size(m)
}
func (m *AuthenticateFingerprint) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateFingerprint.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateFingerprint proto.InternalMessageInfo

func (m *AuthenticateFingerprint) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

type AuthenticateFacebook struct {
	Fingerprint          string   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateFacebook) Reset()         { *m = AuthenticateFacebook{} }
func (m *AuthenticateFacebook) String() string { return proto.CompactTextString(m) }
func (*AuthenticateFacebook) ProtoMessage()    {}
func (*AuthenticateFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46a5b8bd97fe2993, []int{1}
}
func (m *AuthenticateFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateFacebook.Unmarshal(m, b)
}
func (m *AuthenticateFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateFacebook.Marshal(b, m, deterministic)
}
func (dst *AuthenticateFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateFacebook.Merge(dst, src)
}
func (m *AuthenticateFacebook) XXX_Size() int {
	return xxx_messageInfo_AuthenticateFacebook.Size(m)
}
func (m *AuthenticateFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateFacebook proto.InternalMessageInfo

func (m *AuthenticateFacebook) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *AuthenticateFacebook) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type User struct {
	// The id of the user's account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The username of the user's account.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The fingerprint parameter for the user
	Fingerprint string `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The display name of the user.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A URL for an avatar image.
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// Additional information stored as a JSON object.
	Metadata string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The Facebook id in the user's account.
	FacebookId string `protobuf:"bytes,7,opt,name=facebook_id,json=facebookId,proto3" json:"facebook_id,omitempty"`
	// Indicates whether the user is currently online.
	Online bool `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	// The UNIX time when the user was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The UNIX time when the user was last updated.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46a5b8bd97fe2993, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *User) GetFacebookId() string {
	if m != nil {
		return m.FacebookId
	}
	return ""
}

func (m *User) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Session struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46a5b8bd97fe2993, []int{3}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateFingerprint)(nil), "spaceship.api.AuthenticateFingerprint")
	proto.RegisterType((*AuthenticateFacebook)(nil), "spaceship.api.AuthenticateFacebook")
	proto.RegisterType((*User)(nil), "spaceship.api.User")
	proto.RegisterType((*Session)(nil), "spaceship.api.Session")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_api_46a5b8bd97fe2993) }

var fileDescriptor_api_46a5b8bd97fe2993 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x65, 0x27, 0x4d, 0x93, 0x71, 0xcb, 0x61, 0xa9, 0xc0, 0x44, 0x42, 0x0d, 0xb9, 0x90,
	0xd3, 0x46, 0x2a, 0xc7, 0x9e, 0x9a, 0x03, 0x82, 0x4b, 0x55, 0xc5, 0xf4, 0xc2, 0x25, 0x9a, 0xd8,
	0x93, 0x64, 0x54, 0xdb, 0xbb, 0xda, 0x5d, 0x23, 0xf1, 0x77, 0x38, 0xf2, 0xbf, 0xf8, 0x1f, 0x68,
	0xbd, 0x4e, 0x20, 0x50, 0x29, 0xc7, 0xf7, 0xe6, 0x7d, 0x3b, 0xf6, 0xbe, 0x85, 0x4b, 0xd4, 0x3c,
	0x47, 0xcd, 0x52, 0x1b, 0xe5, 0x94, 0xb8, 0xb4, 0x1a, 0x73, 0xb2, 0x3b, 0xd6, 0x12, 0x35, 0x8f,
	0xaf, 0xb7, 0x4a, 0x6d, 0x4b, 0x9a, 0xb7, 0xc3, 0x75, 0xb3, 0x99, 0x3b, 0xae, 0xc8, 0x3a, 0xac,
	0x74, 0xc8, 0x4f, 0x6f, 0xe1, 0xf5, 0x5d, 0xe3, 0x76, 0x54, 0x3b, 0xce, 0xd1, 0xd1, 0x47, 0xae,
	0xb7, 0x64, 0xb4, 0xe1, 0xda, 0x89, 0x09, 0x24, 0x9b, 0x3f, 0x32, 0x8d, 0x26, 0xd1, 0x6c, 0xb4,
	0xfc, 0xdb, 0x9a, 0xde, 0xc3, 0xd5, 0x11, 0x8c, 0x39, 0xad, 0x95, 0x7a, 0x3a, 0x4d, 0x8a, 0x2b,
	0x38, 0x73, 0xea, 0x89, 0xea, 0x34, 0x6e, 0x67, 0x41, 0x4c, 0x7f, 0xc5, 0xd0, 0x7f, 0xb4, 0x64,
	0xc4, 0x0b, 0x88, 0xb9, 0xe8, 0xb8, 0x98, 0x0b, 0x31, 0x86, 0x61, 0x63, 0xc9, 0xd4, 0x58, 0x51,
	0x47, 0x1c, 0xf4, 0xbf, 0xcb, 0x7a, 0xff, 0x2f, 0x7b, 0x07, 0x17, 0x05, 0x5b, 0x5d, 0xe2, 0xf7,
	0x55, 0x7b, 0x42, 0x3f, 0x44, 0x3a, 0xef, 0xde, 0x1f, 0xf2, 0x16, 0x00, 0xbf, 0xa1, 0x43, 0xb3,
	0x6a, 0x4c, 0x99, 0x9e, 0xb5, 0x81, 0x51, 0x70, 0x1e, 0x4d, 0xe9, 0xf7, 0x57, 0xe4, 0xb0, 0x40,
	0x87, 0xe9, 0x20, 0xec, 0xdf, 0x6b, 0x71, 0x0d, 0xc9, 0xa6, 0xfb, 0xf1, 0x15, 0x17, 0xe9, 0x79,
	0x3b, 0x86, 0xbd, 0xf5, 0xb9, 0x10, 0xaf, 0x60, 0xa0, 0xea, 0x92, 0x6b, 0x4a, 0x87, 0x93, 0x68,
	0x36, 0x5c, 0x76, 0x4a, 0xdc, 0x42, 0x92, 0x1b, 0x42, 0x47, 0x2b, 0x5f, 0x4a, 0x3a, 0x9a, 0x44,
	0xb3, 0xe4, 0x66, 0x2c, 0x43, 0x63, 0x72, 0xdf, 0x98, 0xfc, 0xb2, 0x6f, 0x6c, 0x09, 0x21, 0xee,
	0x0d, 0x0f, 0x37, 0xba, 0x38, 0xc0, 0x70, 0x1a, 0x0e, 0x71, 0x6f, 0x4c, 0x3f, 0xc1, 0x79, 0x46,
	0xd6, 0xb2, 0xaa, 0xc5, 0x7b, 0xe8, 0xfb, 0x9b, 0x6c, 0xef, 0x3a, 0xb9, 0x79, 0x29, 0x8f, 0x9e,
	0x8f, 0xf4, 0x65, 0x2c, 0xdb, 0xc0, 0xf3, 0x8d, 0x2d, 0x16, 0xf0, 0xc6, 0x19, 0x99, 0xab, 0x4a,
	0xa2, 0xd6, 0xf6, 0x98, 0x5e, 0x5c, 0x64, 0x5e, 0x66, 0x3b, 0xd6, 0x77, 0x9a, 0x1f, 0xa2, 0xaf,
	0x3d, 0xd4, 0xfc, 0x23, 0xee, 0x65, 0xd9, 0xc3, 0xcf, 0x78, 0x74, 0x98, 0xad, 0x07, 0xed, 0xd7,
	0x7e, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x39, 0x2b, 0x7b, 0xca, 0x02, 0x00, 0x00,
}
